# Generated by Django 5.1.4 on 2024-12-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0004_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
    ]
