# Generated by Django 5.1.4 on 2024-12-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0010_alter_appuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='address',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='customerrelationship',
            old_name='appuser',
            new_name='appuser_id',
        ),
    ]
