# Generated by Django 5.1.4 on 2024-12-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0012_rename_address_id_appuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='created',
            field=models.DateTimeField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='created',
            field=models.DateTimeField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='last_activity',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
