# Generated by Django 5.1.4 on 2024-12-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0014_alter_appuser_created_alter_appuser_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='points',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
